import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { FileSystemCapabilityRegistry } from "../src/registry/filesystem";

const root = resolve(process.env.CAPABILITIES_ROOT || ".");
const outFile = resolve("src/capability-snapshot.ts");
const registry = await FileSystemCapabilityRegistry.scan(root);
const capabilities = registry.listCapabilities().map((capability) => ({
  ...capability,
  rootPath: undefined,
}));

const source = `// Auto-generated by scripts/build-worker.ts. Do not edit by hand.
import type { Capability } from "./registry/types";

export const CAPABILITY_SNAPSHOT = ${JSON.stringify(capabilities, null, 2)} satisfies Capability[];
`;

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, source, "utf-8");

console.log(`Generated ${outFile} with ${capabilities.length} capabilities.`);
